{
  "comments": [
    {
      "key": {
        "uuid": "1aa4ed85_43f9197f",
        "filename": "functest/api/base.py",
        "patchSetId": 22
      },
      "lineNbr": 60,
      "author": {
        "id": 2651
      },
      "writtenOn": "2017-07-28T14:23:56Z",
      "side": 1,
      "message": "Please fix this, api_error is not a configuration in config_functest.yaml anymore.\nIn my opinion, result_handler is actually one kind of exception, something like BadRequest, should be put in error.py",
      "range": {
        "startLine": 60,
        "startChar": 16,
        "endLine": 60,
        "endChar": 51
      },
      "revId": "6c77dc94a48556ff02332f25f144e6916a7813e7",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1aa4ed85_e364c54a",
        "filename": "functest/api/base.py",
        "patchSetId": 22
      },
      "lineNbr": 60,
      "author": {
        "id": 5441
      },
      "writtenOn": "2017-07-28T14:57:44Z",
      "side": 1,
      "message": "Done. Thanks Serena.",
      "parentUuid": "1aa4ed85_43f9197f",
      "range": {
        "startLine": 60,
        "startChar": 16,
        "endLine": 60,
        "endChar": 51
      },
      "revId": "6c77dc94a48556ff02332f25f144e6916a7813e7",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}