{
  "comments": [
    {
      "key": {
        "uuid": "dad5f5cf_10795d2f",
        "filename": "utils/functest_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 363,
      "author": {
        "id": 459
      },
      "writtenOn": "2016-10-18T14:06:09Z",
      "side": 1,
      "message": "shall we raise an exception when criteria is not defined in testcases.yaml? Otherwise the yaml is malformed.",
      "revId": "8ed1c6811a7b85780177a4c3f7f8efeaa85a5721",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}