{
  "comments": [
    {
      "key": {
        "uuid": "5ac10518_ec1f1e08",
        "filename": "testcases/features/sfc/sfc.py",
        "patchSetId": 4
      },
      "lineNbr": 443,
      "author": {
        "id": 5579
      },
      "writtenOn": "2016-11-04T15:59:51Z",
      "side": 1,
      "message": "Wait for ssh connectivity like this:\n\n\n\n    # Check SSH connectivity to VNFs\n    r \u003d 0\n    retries \u003d 100\n    check \u003d [False, False]\n\n    logger.info(\"Checking SSH connectivity to the SFs with ips %s\" % str(ips))\n    while r \u003c retries and not all(check):\n        try:\n            check \u003d [check_ssh(ips[0]), check_ssh(ips[1])]\n        except Exception:\n            logger.exception(\"SSH check failed\")\n            check \u003d [False, False]\n        time.sleep(3)\n        r +\u003d 1\n\n    if not all(check):\n        logger.error(\"Cannot establish SSH connection to the SFs\")\n        sys.exit(1)",
      "range": {
        "startLine": 443,
        "startChar": 0,
        "endLine": 443,
        "endChar": 33
      },
      "revId": "965c89b8703fc42ce4b9d191221c65b1c8043fe1",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}